# Markdown renderer configuration
[goldmark.renderer]
unsafe = true

[goldmark.extensions.passthrough]
enable = true

# LaTeX math support
# https://gohugo.io/content-management/mathematics/
[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[tableOfContents]
endLevel = 3
ordered = true
startLevel = 1

[highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
style = "solarized-dark"
