baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Zechao'
theme = ["hugo-theme-stack", "almeida-cv"]

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

[languages]
[languages.en]
languageName = "English"
title = "Example Site"
weight = 1
[languages.en.params.sidebar]
subtitle = "Example description"
[languages.zh-cn]
languageName = "中文"
title = "演示站点"
weight = 2
[languages.zh-cn.params.sidebar]
subtitle = "演示说明"
[languages.ar]
languageName = "عربي"
languagedirection = "rtl"
title = "موقع تجريبي"
weight = 3
[languages.ar.params.sidebar]
subtitle = "وصف تجريبي"


[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#e3bfb8"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#e3bfb8"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = false
