baseURL = 'https://www.devzechao.com/'
languageCode = 'en-us'
theme = ["hugo-theme-stack", "almeida-cv"]
# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage = "en"

[services.disqus]
shortname = "devzechao"

[languages]
[languages.en]
languageName = "English"
title = "Zechao Jin"
weight = 1
[languages.en.params.sidebar]
subtitle = "A software engineer"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/zechao.jpg"

[params.article]
math = false
toc = true
readingTime = true

[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"


# param for almeida-cv
[params]
mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true
favicon = ""

# param for almeida-cv
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#e3bfb8"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#e3bfb8"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = true
